name: simple_todo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  dynamic_color: ^1.6.2
  flutter_localizations:
    sdk: flutter
  intl: any
  great_list_view: ^0.2.3
  flutter_svg: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.4+2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.svg
    - assets/logo_dark.svg
